title: BeagleBoard.org, GSoC 2019
author: Pratim Ugale
email: pratim.ugale@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  This is my personal website which I made after being selected as a Student Developer under the program, Google Summer of Code. I'll be developing open source code for BeagleBoard.org for my project "PRU User Space API"

#avatar: /assets/pratim_photo.jpg

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: pratimugaley
    github:  pratimugale
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    instagram: pratimugale
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- about.md
- project_updates.md
- notes.md


# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
